# Generated by Django 4.2.3 on 2023-08-09 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
            },
        ),
        migrations.CreateModel(
            name='ChatFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(null=True)),
                ('option', models.IntegerField(null=True)),
                ('params', models.TextField(blank=True, max_length=1000, null=True)),
                ('ok_message', models.TextField(blank=True, max_length=1000, null=True)),
                ('nook_message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'flow',
                'verbose_name_plural': 'flow',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('contacts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_wa', models.CharField(max_length=200)),
                ('whatsapp_url', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Credenciales',
                'verbose_name_plural': 'Credenciales',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('msg_recibed', models.TextField(max_length=1000)),
                ('msg_sended', models.TextField(blank=True, max_length=1000, null=True)),
                ('id_wap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.client')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ClientChatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('coment', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.client')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.carmodel')),
            ],
            options={
                'verbose_name': 'estatus',
                'verbose_name_plural': 'estatus',
            },
        ),
    ]
