# Generated by Django 4.2.3 on 2023-08-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='whatsapp_url',
            field=models.CharField(max_length=150),
        ),
    ]
