# Generated by Django 4.2.3 on 2023-08-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_credentials_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recibido',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
